[package]
edition = "2021"
name = "resticular"
version = "0.1.0"
[dependencies]
notify = "4.0.17"
pulldown-cmark = "0.9.1"
serde = "*"
serde_derive = "*"
tera = "*"
thiserror = "*"
toml = "*"
ws = "*"
lol_html = "0.3.1"

[lib]
name = "resticular"
path = "src/lib/mod.rs"
