[package]
edition = "2021"
name = "resticular"
version = "0.1.0"
[dependencies]
downcast-rs = "*"
lol_html = "*"
notify = "4.0.17"
pulldown-cmark = "0.9.1"
serde = "*"
serde_derive = "*"
tera = "*"
thiserror = "*"
toml = "*"
ws = "*"
minify-html = "0.8.0"
mopa = "0.2.2"
[lib]
name = "resticular"
path = "src/lib/mod.rs"
